# Railway Configuration for WebsiteBuilder API
# This file configures how Railway builds and deploys your .NET application

[build]
# Use Nixpacks builder for .NET
builder = "NIXPACKS"
# Build command for .NET 8
buildCommand = "dotnet restore && dotnet publish -c Release -o out"

[deploy]
# Start command for the published app
startCommand = "dotnet out/WebsiteBuilderAPI.dll"
# Health check endpoint
healthcheckPath = "/api/health"
# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Number of instances
numReplicas = 1
# Region (optional - Railway will auto-select if not specified)
# region = "us-west1"